port: 8080
swagger_enabled: true
auto_open_browser: false

db_list:
  default_db_name: test
  connect_list:
    - name: test
      db_type: sqlite
      db_path: ./data/test.db
      max_open_conns: 20
      max_idle_conns: 10
      conn_max_lifetime: 30

#    - name: analytics_db
#      db_type: postgres
#      db_path: host=127.0.0.1 port=5432 user=admin password=secret dbname=analytics sslmode=disable
#      max_open_conns: 50
#      # max_idle_conns 未配置 → nil
#      # conn_max_lifetime 未配置 → nil
