package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

type commonResponse struct {
	Code    int             `json:"code"`
	Message string          `json:"message"`
	Data    json.RawMessage `json:"data"`
}

type productData struct {
	ID          uint    `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type versionData struct {
	ID          uint   `json:"id"`
	ProductID   uint   `json:"product_id"`
	VersionCode string `json:"version_code"`
}

type licenseData struct {
	ID            uint    `json:"id"`
	ProductID     uint    `json:"product_id"`
	LicenseKey    string  `json:"license_key"`
	ValidityHours int     `json:"validity_hours"`
	Status        int     `json:"status"`
	Remark        *string `json:"remark"`
}

type registerResult struct {
	NodeID             uint   `json:"node_id"`
	LicenseID          uint   `json:"license_id"`
	ProductID          uint   `json:"product_id"`
	LicenseKey         string `json:"license_key"`
	LicenseStatus      int    `json:"license_status"`
	MaxNodes           int    `json:"max_nodes"`
	CurrentNodeCount   int    `json:"current_node_count"`
	MaxConcurrent      int    `json:"max_concurrent"`
	HeartbeatInterval  int    `json:"heartbeat_interval"`
	BindingEstablished bool   `json:"binding_established"`
}

type heartbeatResult struct {
	Online bool `json:"online"`
}

type client struct {
	baseURL string
	http    *http.Client
}

func main() {
	baseURL := flag.String("server", "http://localhost:8080", "nexus-core server base URL")
	productName := flag.String("product-name", "", "demo product name; default creates a unique name")
	versionCode := flag.String("version", "1.0.0", "demo product version")
	deviceCode := flag.String("device", "demo-device-001", "demo node device code")
	heartbeatCount := flag.Int("heartbeats", 3, "number of heartbeat requests to send")
	heartbeatInterval := flag.Duration("heartbeat-interval", time.Second, "delay between heartbeat requests")
	maxNodes := flag.Int("max-nodes", 2, "license max bound nodes; 0 means unlimited")
	maxConcurrent := flag.Int("max-concurrent", 1, "license max online concurrent nodes; 0 means unlimited")
	validityHours := flag.Int("validity-hours", 24, "license validity hours after activation")
	flag.Parse()

	name := strings.TrimSpace(*productName)
	if name == "" {
		name = fmt.Sprintf("demo-product-%s", time.Now().Format("20060102-150405"))
	}

	c := client{
		baseURL: strings.TrimRight(*baseURL, "/"),
		http: &http.Client{
			Timeout: 10 * time.Second,
		},
	}

	if err := c.run(name, *versionCode, *deviceCode, *heartbeatCount, *heartbeatInterval, *maxNodes, *maxConcurrent, *validityHours); err != nil {
		fmt.Printf("demo failed: %v\n", err)
		return
	}

	fmt.Println("demo completed")
}

func (c client) run(productName, versionCode, deviceCode string, heartbeatCount int, heartbeatInterval time.Duration, maxNodes, maxConcurrent, validityHours int) error {
	description := "demo product generated by cmd/demo-product"

	product, err := postJSON[productData](c, "/products", map[string]interface{}{
		"name":        productName,
		"description": description,
	})
	if err != nil {
		return fmt.Errorf("create product: %w", err)
	}
	fmt.Printf("created product: id=%d name=%s\n", product.ID, product.Name)

	version, err := postJSON[versionData](c, "/products/versions", map[string]interface{}{
		"product_id":     product.ID,
		"version_code":   versionCode,
		"release_method": 0,
		"description":    "demo version",
	})
	if err != nil {
		return fmt.Errorf("create product version: %w", err)
	}
	fmt.Printf("created and released version: id=%d code=%s\n", version.ID, version.VersionCode)

	license, err := postJSON[licenseData](c, "/licenses", map[string]interface{}{
		"product_id":     product.ID,
		"validity_hours": validityHours,
		"max_nodes":      maxNodes,
		"max_concurrent": maxConcurrent,
		"remark":         "demo license",
	})
	if err != nil {
		return fmt.Errorf("create license: %w", err)
	}
	fmt.Printf("created license: id=%d key=%s\n", license.ID, license.LicenseKey)

	register, err := postJSON[registerResult](c, "/access/register", map[string]interface{}{
		"device_code":  deviceCode,
		"license_key":  license.LicenseKey,
		"product_id":   product.ID,
		"version_code": versionCode,
	})
	if err != nil {
		return fmt.Errorf("register node: %w", err)
	}
	fmt.Printf(
		"registered node: node_id=%d license_status=%d current_nodes=%d binding_created=%t\n",
		register.NodeID,
		register.LicenseStatus,
		register.CurrentNodeCount,
		register.BindingEstablished,
	)

	for i := 1; i <= heartbeatCount; i++ {
		heartbeat, err := postJSON[heartbeatResult](c, "/access/heartbeat", map[string]interface{}{
			"device_code":  deviceCode,
			"license_key":  license.LicenseKey,
			"product_id":   product.ID,
			"version_code": versionCode,
		})
		if err != nil {
			return fmt.Errorf("heartbeat %d: %w", i, err)
		}
		fmt.Printf("heartbeat %d/%d: online=%t\n", i, heartbeatCount, heartbeat.Online)
		if i < heartbeatCount {
			time.Sleep(heartbeatInterval)
		}
	}

	return nil
}

func postJSON[T any](c client, path string, payload interface{}) (T, error) {
	var zero T

	body, err := json.Marshal(payload)
	if err != nil {
		return zero, err
	}

	req, err := http.NewRequest(http.MethodPost, c.baseURL+path, bytes.NewReader(body))
	if err != nil {
		return zero, err
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.http.Do(req)
	if err != nil {
		return zero, err
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return zero, err
	}

	var common commonResponse
	if err := json.Unmarshal(raw, &common); err != nil {
		return zero, fmt.Errorf("invalid response status=%d body=%s: %w", resp.StatusCode, string(raw), err)
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 || common.Code < 200 || common.Code >= 300 {
		return zero, fmt.Errorf("status=%d code=%d message=%s body=%s", resp.StatusCode, common.Code, common.Message, string(raw))
	}
	if len(common.Data) == 0 || string(common.Data) == "null" || string(common.Data) == `""` {
		return zero, nil
	}

	var result T
	if err := json.Unmarshal(common.Data, &result); err != nil {
		return zero, fmt.Errorf("decode data: %w", err)
	}
	return result, nil
}
